name: Hello World Docker Action
description: A Container Action for saying Hello World!"

inputs:
  who-to-greet:
    default: "world"
    description: "Who to greet"
outputs:
  time:
    description: "The time this was run"
runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - ${{ inputs.who-to-greet }}
