name: Hello World Docker CI

on: [ push, workflow_dispatch ]

jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - id: hello-action
        uses: hello-world-docker-action
        with:
          who-to-greet: "Connor"
      - run: echo "The time this action was run was at ${{ steps.hello-action.outputs.time }}"
